{% set version = "2.15.3" %}

package:
  name: dataclasses-jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dataclasses-jsonschema/dataclasses-jsonschema-{{ version }}.tar.gz
  sha256: 607b86432a45d9e0b4170605284132e1aac76e7a92f518989141ab4524549058

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    # TODO: remove pin after https://github.com/s-knibbs/dataclasses-jsonschema/issues/181
    - python >=3.7,<3.10
    - setuptools-scm
  run:
    - dataclasses
    - jsonschema
    - python >=3.7,<3.10
    - python-dateutil
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - dataclasses_jsonschema
  commands:
    - pip check
    - pytest tests -vv --cov dataclasses_jsonschema --cov-report=term-missing:skip-covered --cov-fail-under=92 --no-cov-on-fail
  requires:
    - apispec
    - apispec-webframeworks
    - flask
    - pip
    - pytest-cov
    - pytest-ordering
    - python-fastjsonschema

about:
  home: https://github.com/s-knibbs/dataclasses-jsonschema
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
